[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "simple-mouse-jiggler"
version = "0.1.1"
description = "Jiggle the mouse to prevent the computer from going to sleep."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "click~=8.3",
    "rich~=15.0",
    "PyAutoGUI~=0.9",
]

[project.urls]
Documentation = "https://github.com/yt0123/mouse-jiggler"
Source = "https://github.com/yt0123/mouse-jiggler/blob/main/src"

[project.scripts]
jiggle = "mouse_jiggler.cli:jiggle"
